### ISSUE TITLE
The model switcher does not seem to work anymore

### ISSUE THREAD

**Issue by tpeg5stan** [hydrotho/ChatGPT_Model_Switcher#20]
Hello and thanks for your great script ! 

It used to be working in November 2023, but it does not seem to be working as of today. I have tried on different browsers and computers. Am I the only one to face this problem ? Could you try and solve that ?

Thanks in advance

**Comment by hydrotho** [comment]
Please give a detailed description of the problems you are experiencing.

**Comment by pimvanberlo** [comment]
It could be that the switch is turned off without you knowing. You're running 2.0.1; on this version the on/off switch is no longer visible. Can you update to 2.0.2 and test again?

https://raw.githubusercontent.com/hydrotho/ChatGPT_Model_Switcher/main/dist/chatgpt-model-switcher.user.js

**Comment by hydrotho** [comment]
As ChatGPT becomes more productized, OpenAI has implemented stricter limitations. Also, due to personal work commitments and limited time and energy, this project can no longer guarantee to override the usage limits of the GPT-4 model on the ChatGPT web interface. If you are capable, you are welcome to contribute to this project.

**Comment by hydrotho** [comment]
Also, based on the screenshot it looks like you are running a version prior to v2.0.2, please upgrade to the latest version to get the switch buttons back.
