### ISSUE TITLE
Not switching 

### ISSUE THREAD

**Issue by Volkyz** [hydrotho/ChatGPT_Model_Switcher#33]
It doesn’t work anymore can u please fix it

**Comment by hydrotho** [comment]
OpenAI is redirecting all requests to chatgpt.com. Look at your browser's address bar to confirm.

The UserScript wasn't working because it needed to match a specific domain name.

**Comment by hydrotho** [comment]
I'll fix it later.

**Comment by whl2638916** [comment]
Hey there, sorry to bother you. I wanted to ask, it seems like when I select the 'GPT-4 (Mobile)' model, I get a prompt saying 'Hmm...something seems to have gone wrong.' Is it because this model became unusable after an update to ChatGPT, or is there some other reason? Thanks for the reply and ongoing support with this plugin!

**Comment by Volkyz** [comment]
> OpenAI is redirecting all requests to chatgpt.com. Look at your browser's address bar to confirm.
> 
> The UserScript wasn't working because it needed to match a specific domain name.

thank you man i hope you fix it cause it doesn't switch
