### ISSUE TITLE
Superpower ChatGPT Google Store Plugin has a large number of models, while this plugin only has a few.

### ISSUE THREAD

**Issue by lulu-sk** [hydrotho/ChatGPT_Model_Switcher#4]
![image](https://github.com/hydrotho/ChatGPT_Model_Switcher/assets/58587930/f570e447-7e90-4d29-9e9d-13af189aea47)

**Comment by lulu-sk** [comment]
https://github.com/saeedezzati/superpower-chatgpt

**Comment by hydrotho** [comment]
Thanks for your feedback. 

However, I'd like to clarify that the models labeled as `Unofficial` in Superpower ChatGPT may not actually be usable. In fact, as far as I know, these models can currently only be accessed via the OpenAI API.

Furthermore, there are some significant differences between the web version of ChatGPT and the OpenAI API. For example, GPT-3.5 in ChatGPT actually uses `text-davinci-002-render-sha` instead of `gpt-3.5-turbo`.

To know which models are available in ChatGPT, you can use your browser's developer tools to inspect this request: https://chat.openai.com/backend-api/models?history_and_training_disabled=false. The returned JSON object lists all the models you can use.

For the list of models available via the OpenAI API, please refer to https://platform.openai.com/docs/models.

If you have any other questions, feel free to ask.

**Comment by lulu-sk** [comment]
> 感谢您的反馈意见。
> 
> 但是，我想澄清的是，标记为的模型 `Unofficial`在 Superpower ChatGPT 中可能实际上无法使用。 事实上，据我所知，这些模型目前只能通过 OpenAI API 访问。
> 
> 此外，ChatGPT 的网络版本和 OpenAI API 之间存在一些显着差异。 例如ChatGPT中的GPT-3.5实际上使用 `text-davinci-002-render-sha`代替 `gpt-3.5-turbo`.
> 
> 要了解 ChatGPT 中可用的模型，您可以使用浏览器的开发人员工具检查此请求： [https://chat.openai.com/backend-api/models ](https://chat.openai.com/backend-api/models?history_and_training_disabled=false) ?history_and_training_disabled=false 。 返回的 JSON 对象列出了您可以使用的所有模型。
> 
> 有关通过 OpenAI API 提供的模型列表，请参阅 [https://platform.openai.com/docs/models ](https://platform.openai.com/docs/models) 。
> 
> 如果您还有其他问题，请随时询问。

![image](https://github.com/hydrotho/ChatGPT_Model_Switcher/assets/58587930/2c14e1ac-ed60-4cbd-ad2f-a25ce0aaae50)

Actually, the plugin author has also mentioned and labeled this as an experimental feature. The author is also observing feedback from users on Discord. Some people have suggested that if they don't use 32k text, they tend to forget what was said. Therefore, I believe it could be effective.
